INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('GREETINGS', 'Welcome to Customer Portal!', 'Добро пожаловать на клиентский портал!', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('FIRST_NAME', 'First Name', 'Имя', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('LAST_NAME', 'Last Name', 'Фамилия', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('BIRTH_DATE', 'Birth Date', 'Дата рождения', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('GENDER', 'Gender', 'Пол', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('EMAIL', 'Email', 'Эл.почта', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('ADDRESS', 'Address', 'Адрес', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('GENDER_MALE', 'Male', 'Мужской', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('GENDER_FEMALE', 'Female', 'Женский', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('ADD_NEW', 'Add new', 'Добавить', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('FIRST', 'first', '<<', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('PREV', 'prev', '<', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('NEXT', 'next', '>', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('LAST', 'last', '>>', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('SEARCH', 'Search', 'Поиск', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('LAST_UPDATE', 'Last Update', 'Обновлено', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('NO_ROWS_SELECTED', 'No rows selected', 'Нет доступных записей', '');

INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('MANDATORY_FIELDS_CANNOT_BE_EMPTY', 'Mandatory(*) fields cannot be empty', 'Обязательные(*) поля не могут быть пустыми', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('PLEASE_PROVIDE_VALID_BIRTH_DATE', 'Please provide valid Birth Date', 'Пожалуйста введите корректную дату рождения', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('PLEASE_PROVIDE_VALID_BIRTH_DATE_IN_FORMAT', 'Please provide valid Birth Date in format YYYY-MM-DD', 'Пожалуйста введите корректную дату рождения в формате YYYY-MM-DD', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('PLEASE_PROVIDE_VALID_BIRTH_DATE_FROM_TO', 'Please provide valid Birth Date from 18 till 60 years', 'Пожалуйста введите корректную дату рождения от 18 до 60 лет', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('GENDER_FIELDS_SUPPORTS_ONLY_VALUES', 'Gender field supports only Male and Female values', 'Поле Пол поддерживает только значения Male и Female', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('PLEASE_PROVIDE_VALID_EMAIL', 'Please provide valid Email', 'Пожалуйста введите корректный адрес электронной почты', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('INVALID_OPERATION_PLEASE_RELOAD', 'Invalid operation, please re-load the page', 'Некорректное обращение к системе, пожалуйста, перезагрузите страницу', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('NEW_RECORD_SUCCESSFULLY_ADDED', 'New record successfully added', 'Новая запись успешно добавлена', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('VALUE_CHANGED_BY_ANOTHER_USER_RELOADED', 'Value changed by another user session, please verify new value and update it if necessary, page reloaded to reflect last changes', 'Значение было изменено другим пользователем, проверьте значение и обновите если это всё ещё необходимо, страница обновлена и отображает актуальную информацию', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('VALUE_ALREADY_UPDATED_BY_ANOTHER_USER_RELOADED', 'Value already updated by another user session, page reloaded, actual value: ', 'Значение уже обновлено другим пользователем, страница обновлена, актуальное значение: ', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('UPDATED_SUCCESSFULLY_OLD_VALUE', 'Updated successfully, old value: "', 'Успешно обновлено, старое значение: "', '');
INSERT INTO lngdata (lid, language_1, language_2, language_3) VALUES ('NEW_VALUE', '", new value: "', '", новое значение: "', '');
